version: "3.9"
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - '8080:80'
        volumes:
            - './app:/app'
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - './app:/app'

    php-cli:
        build:
            context: docker/php-cli
        volumes:
            - './app:/app'

    mariadb:
        image: mariadb:10.1.37
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: userapp
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
volumes:
    db_data:
